apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
type: Opaque
data:
    admin: ENC[AES256_GCM,data:tDqFXh71rI+044XI,iv:RQGhmZ7/X5XrtXkpqQA9+Sn0coIPstUWzC50j1qDYMs=,tag:/hmvvoBacTJkFWw3J+zZMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m74ukye349p80duvy953d7vrpzvd60jx0vr49ew5df2rg2aj4u2sjpuv25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R2xpUVJiQzc0MklKczlZ
            QktWUUtaUlNaeHJ4elFkcjhXeEdnQXFKK1RnCkNaZThMNHhBMFBPVjhSN2paODFG
            QUxwVVVmR1BncTNBMExWL3B0QTRzSEEKLS0tIE1iL1lRWWgycnRjNDY3NXYwU0Nr
            VEJua01KOUtYSXNCNjVSdVpGS1NURVUKJ15YhBteUifjC13/wj/cweD7ozNxVIyX
            4JHF3BE3grXHJNyyV4W33jA7XMEX645uWO8oS8WuCDyAkL8uNHdAhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-04T01:29:27Z"
    mac: ENC[AES256_GCM,data:nBzG1qLcov28y7TshjShpYkWU04edoF6lemDQlvQLGQgLFmgTcMwVkanMN1YRpQKDtREKVccelEkYayU73zZbWhhg88F7GvTLnptboRZNz2/N0TkVLbZSzAHpIynUrjvIZ5P0+d+KNBQ0cOceLVJWx8ORPyAtm2+oHGSdZ3k0Zc=,iv:sqm0hZJwmCDoqTMxmh82lvOmGQb92FLn259W/Lz1fzo=,tag:Czg8ZJ9Vv6+9tFz+RsevbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
