apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: firefly-iii-initdb
spec:
  description: Postgres database cluster for firefly-iii
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-30-bookworm
  instances: 3

  inheritedMetadata:
    labels:
      app: firefly-iii-database

  bootstrap:
    initdb:
      database: firefly-iii
      owner: firefly

  # externalClusters:
  #   - name: clusterBackup
  #     barmanObjectStore:
  #       destinationPath: "s3://hl-database-clump/linkding/"
  #       serverName: linkding-backup
  #       s3Credentials:
  #         accessKeyId:
  #           name: aws-creds
  #           key: ACCESS_KEY_ID
  #         secretAccessKey:
  #           name: aws-creds
  #           key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: s3://hl-database-clump/firefly-iii/
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
    retentionPolicy: 14d

  monitoring:
    enablePodMonitor: true

  storage:
    size: 8Gi
