apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: firefly
resources:
  - ../../base/firefly
  - database.yaml
  - database-secret.yaml
  - configmap.yaml
  - scheduled-backup.yaml
  - cloudflare.yaml
  - cloudflare-secret.yaml
