apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly
spec:
  interval: 1h
  chart:
    spec:
      chart: firefly-iii
      version: "1.9.11"
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: firefly
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 33
      runAsGroup: 33
      fsGroup: 33
    config:
      envValueFrom:
        DB_HOST:
          secretKeyRef:
            name: firefly-iii-database-cluster-app
            key: host
        DB_PORT:
          secretKeyRef:
            name: firefly-iii-database-cluster-app
            key: port
        DB_DATABASE:
          secretKeyRef:
            name: firefly-iii-database-cluster-app
            key: dbname
        DB_USERNAME:
          secretKeyRef:
            name: firefly-iii-database-cluster-app
            key: username
        DB_PASSWORD:
          secretKeyRef:
            name: firefly-iii-database-cluster-app
            key: password
        TZ:
          configMapKeyRef:
            name: firefly-iii-configmap
            key: TZ
        DB_CONNECTION:
          configMapKeyRef:
            name: firefly-iii-configmap
            key: DB_CONNECTION
