apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: firefly
spec:
  interval: 1h
  chart:
    spec:
      chart: firefly-iii
      version: "1.9.4"
      sourceRef:
        kind: HelmRepository
        name: firefly-iii
        namespace: firefly
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    persistence:
      enabled: false
