apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-database-cluster
spec:
  description: Postgres database cluster for linkding
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-30-bookworm
  instances: 3

  inheritedMetadata:
    labels:
      app: linkding-database

  bootstrap:
    recovery:
      source: clusterBackup
      database: linkding
      owner: linkding

  externalClusters:
    - name: clusterBackup
      barmanObjectStore:
        destinationPath: s3://hl-database-clump/linkding/
        s3Credentials:
          accessKeyId:
            name: aws-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: aws-creds
            key: ACCESS_SECRET_KEY

  backup:
    barmanObjectStore:
      destinationPath: s3://hl-database-clump/linkding/
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: 14d

  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi
