apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-database-cluster
spec:
  description: Postgres database cluster for linkding
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-30-bookworm
  instances: 3

  inheritedMetadata:
    labels:
      app: linkding-database


  bootstrap:
    initdb:
      database: linkding

  monitoring:
    enablePodMonitor: true

  storage:
    size: 1Gi
