apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.2"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  valuesFrom:
    - kind: Secret
      name: grafana-credentials
      valuesKey: admin
      targetPath: grafana.adminPassword
  values:

    prometheus:
      prometheusSpec:
        # allows servicemonitor and podmonitor discovery across all namespaces
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false

    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - graf.dzilic.net
        tls:
          - secretName: grafana-tls-secret
            hosts:
              - graf.dzilic.net
