apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-server
  namespace: minecraft
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: "4.26.3"

      # version: "58.x"

      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: minecraft
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    resources:
      requests:
        memory: 8192Mi
        cpu: 2000m
    minecraftServer:
      eula: "TRUE"
      difficulty: hard
      whitelist: OatmealRecipes, RogueAccessPoint, ajka_, flooflyy, Tata_Chasim
      ops: OatmealRecipes, RogueAccessPoint, ajka_, flooflyy, Tata_Chasim
      type: "PAPER"
      onlineMode: false
      overrideServerProperties: true
      memory: 8192M
    extraVolumes:
      - volumeMounts:
          - name: spigot
            mountPath: /data/spigot.yml
            readOnly: false
            subPath: spigot.yml
        volumes:
          - name: spigot
            configMap:
              name: spigot-config
    persistence:
      dataDir:
        enabled: true
        Size: 2Gi
